package odoo

import (
	"fmt"
)

// FleetVehicleLogFuel represents fleet.vehicle.log.fuel model.
type FleetVehicleLogFuel struct {
	LastUpdate    *Time      `xmlrpc:"__last_update,omptempty"`
	Amount        *Float     `xmlrpc:"amount,omptempty"`
	AutoGenerated *Bool      `xmlrpc:"auto_generated,omptempty"`
	CompanyId     *Many2One  `xmlrpc:"company_id,omptempty"`
	ContractId    *Many2One  `xmlrpc:"contract_id,omptempty"`
	CostAmount    *Float     `xmlrpc:"cost_amount,omptempty"`
	CostId        *Many2One  `xmlrpc:"cost_id,omptempty"`
	CostIds       *Relation  `xmlrpc:"cost_ids,omptempty"`
	CostSubtypeId *Many2One  `xmlrpc:"cost_subtype_id,omptempty"`
	CostType      *Selection `xmlrpc:"cost_type,omptempty"`
	CreateDate    *Time      `xmlrpc:"create_date,omptempty"`
	CreateUid     *Many2One  `xmlrpc:"create_uid,omptempty"`
	CurrencyId    *Many2One  `xmlrpc:"currency_id,omptempty"`
	Date          *Time      `xmlrpc:"date,omptempty"`
	Description   *String    `xmlrpc:"description,omptempty"`
	DisplayName   *String    `xmlrpc:"display_name,omptempty"`
	Id            *Int       `xmlrpc:"id,omptempty"`
	InvRef        *String    `xmlrpc:"inv_ref,omptempty"`
	Liter         *Float     `xmlrpc:"liter,omptempty"`
	Name          *String    `xmlrpc:"name,omptempty"`
	Notes         *String    `xmlrpc:"notes,omptempty"`
	Odometer      *Float     `xmlrpc:"odometer,omptempty"`
	OdometerId    *Many2One  `xmlrpc:"odometer_id,omptempty"`
	OdometerUnit  *Selection `xmlrpc:"odometer_unit,omptempty"`
	ParentId      *Many2One  `xmlrpc:"parent_id,omptempty"`
	PricePerLiter *Float     `xmlrpc:"price_per_liter,omptempty"`
	PurchaserId   *Many2One  `xmlrpc:"purchaser_id,omptempty"`
	VehicleId     *Many2One  `xmlrpc:"vehicle_id,omptempty"`
	VendorId      *Many2One  `xmlrpc:"vendor_id,omptempty"`
	WriteDate     *Time      `xmlrpc:"write_date,omptempty"`
	WriteUid      *Many2One  `xmlrpc:"write_uid,omptempty"`
}

// FleetVehicleLogFuels represents array of fleet.vehicle.log.fuel model.
type FleetVehicleLogFuels []FleetVehicleLogFuel

// FleetVehicleLogFuelModel is the odoo model name.
const FleetVehicleLogFuelModel = "fleet.vehicle.log.fuel"

// Many2One convert FleetVehicleLogFuel to *Many2One.
func (fvlf *FleetVehicleLogFuel) Many2One() *Many2One {
	return NewMany2One(fvlf.Id.Get(), "")
}

// CreateFleetVehicleLogFuel creates a new fleet.vehicle.log.fuel model and returns its id.
func (c *Client) CreateFleetVehicleLogFuel(fvlf *FleetVehicleLogFuel) (int64, error) {
	ids, err := c.CreateFleetVehicleLogFuels([]*FleetVehicleLogFuel{fvlf})
	if err != nil {
		return -1, err
	}
	if len(ids) == 0 {
		return -1, nil
	}
	return ids[0], nil
}

// CreateFleetVehicleLogFuel creates a new fleet.vehicle.log.fuel model and returns its id.
func (c *Client) CreateFleetVehicleLogFuels(fvlfs []*FleetVehicleLogFuel) ([]int64, error) {
	var vv []interface{}
	for _, v := range fvlfs {
		vv = append(vv, v)
	}
	return c.Create(FleetVehicleLogFuelModel, vv)
}

// UpdateFleetVehicleLogFuel updates an existing fleet.vehicle.log.fuel record.
func (c *Client) UpdateFleetVehicleLogFuel(fvlf *FleetVehicleLogFuel) error {
	return c.UpdateFleetVehicleLogFuels([]int64{fvlf.Id.Get()}, fvlf)
}

// UpdateFleetVehicleLogFuels updates existing fleet.vehicle.log.fuel records.
// All records (represented by ids) will be updated by fvlf values.
func (c *Client) UpdateFleetVehicleLogFuels(ids []int64, fvlf *FleetVehicleLogFuel) error {
	return c.Update(FleetVehicleLogFuelModel, ids, fvlf)
}

// DeleteFleetVehicleLogFuel deletes an existing fleet.vehicle.log.fuel record.
func (c *Client) DeleteFleetVehicleLogFuel(id int64) error {
	return c.DeleteFleetVehicleLogFuels([]int64{id})
}

// DeleteFleetVehicleLogFuels deletes existing fleet.vehicle.log.fuel records.
func (c *Client) DeleteFleetVehicleLogFuels(ids []int64) error {
	return c.Delete(FleetVehicleLogFuelModel, ids)
}

// GetFleetVehicleLogFuel gets fleet.vehicle.log.fuel existing record.
func (c *Client) GetFleetVehicleLogFuel(id int64) (*FleetVehicleLogFuel, error) {
	fvlfs, err := c.GetFleetVehicleLogFuels([]int64{id})
	if err != nil {
		return nil, err
	}
	if fvlfs != nil && len(*fvlfs) > 0 {
		return &((*fvlfs)[0]), nil
	}
	return nil, fmt.Errorf("id %v of fleet.vehicle.log.fuel not found", id)
}

// GetFleetVehicleLogFuels gets fleet.vehicle.log.fuel existing records.
func (c *Client) GetFleetVehicleLogFuels(ids []int64) (*FleetVehicleLogFuels, error) {
	fvlfs := &FleetVehicleLogFuels{}
	if err := c.Read(FleetVehicleLogFuelModel, ids, nil, fvlfs); err != nil {
		return nil, err
	}
	return fvlfs, nil
}

// FindFleetVehicleLogFuel finds fleet.vehicle.log.fuel record by querying it with criteria.
func (c *Client) FindFleetVehicleLogFuel(criteria *Criteria) (*FleetVehicleLogFuel, error) {
	fvlfs := &FleetVehicleLogFuels{}
	if err := c.SearchRead(FleetVehicleLogFuelModel, criteria, NewOptions().Limit(1), fvlfs); err != nil {
		return nil, err
	}
	if fvlfs != nil && len(*fvlfs) > 0 {
		return &((*fvlfs)[0]), nil
	}
	return nil, fmt.Errorf("fleet.vehicle.log.fuel was not found with criteria %v", criteria)
}

// FindFleetVehicleLogFuels finds fleet.vehicle.log.fuel records by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleLogFuels(criteria *Criteria, options *Options) (*FleetVehicleLogFuels, error) {
	fvlfs := &FleetVehicleLogFuels{}
	if err := c.SearchRead(FleetVehicleLogFuelModel, criteria, options, fvlfs); err != nil {
		return nil, err
	}
	return fvlfs, nil
}

// FindFleetVehicleLogFuelIds finds records ids by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleLogFuelIds(criteria *Criteria, options *Options) ([]int64, error) {
	ids, err := c.Search(FleetVehicleLogFuelModel, criteria, options)
	if err != nil {
		return []int64{}, err
	}
	return ids, nil
}

// FindFleetVehicleLogFuelId finds record id by querying it with criteria.
func (c *Client) FindFleetVehicleLogFuelId(criteria *Criteria, options *Options) (int64, error) {
	ids, err := c.Search(FleetVehicleLogFuelModel, criteria, options)
	if err != nil {
		return -1, err
	}
	if len(ids) > 0 {
		return ids[0], nil
	}
	return -1, fmt.Errorf("fleet.vehicle.log.fuel was not found with criteria %v and options %v", criteria, options)
}
