package odoo

import (
	"fmt"
)

// FleetVehicleLogContract represents fleet.vehicle.log.contract model.
type FleetVehicleLogContract struct {
	LastUpdate                  *Time      `xmlrpc:"__last_update,omptempty"`
	Active                      *Bool      `xmlrpc:"active,omptempty"`
	ActivityDateDeadline        *Time      `xmlrpc:"activity_date_deadline,omptempty"`
	ActivityExceptionDecoration *Selection `xmlrpc:"activity_exception_decoration,omptempty"`
	ActivityExceptionIcon       *String    `xmlrpc:"activity_exception_icon,omptempty"`
	ActivityIds                 *Relation  `xmlrpc:"activity_ids,omptempty"`
	ActivityState               *Selection `xmlrpc:"activity_state,omptempty"`
	ActivitySummary             *String    `xmlrpc:"activity_summary,omptempty"`
	ActivityTypeId              *Many2One  `xmlrpc:"activity_type_id,omptempty"`
	ActivityUserId              *Many2One  `xmlrpc:"activity_user_id,omptempty"`
	Amount                      *Float     `xmlrpc:"amount,omptempty"`
	AutoGenerated               *Bool      `xmlrpc:"auto_generated,omptempty"`
	CompanyId                   *Many2One  `xmlrpc:"company_id,omptempty"`
	ContractId                  *Many2One  `xmlrpc:"contract_id,omptempty"`
	CostAmount                  *Float     `xmlrpc:"cost_amount,omptempty"`
	CostFrequency               *Selection `xmlrpc:"cost_frequency,omptempty"`
	CostGenerated               *Float     `xmlrpc:"cost_generated,omptempty"`
	CostId                      *Many2One  `xmlrpc:"cost_id,omptempty"`
	CostIds                     *Relation  `xmlrpc:"cost_ids,omptempty"`
	CostSubtypeId               *Many2One  `xmlrpc:"cost_subtype_id,omptempty"`
	CostType                    *Selection `xmlrpc:"cost_type,omptempty"`
	CreateDate                  *Time      `xmlrpc:"create_date,omptempty"`
	CreateUid                   *Many2One  `xmlrpc:"create_uid,omptempty"`
	CurrencyId                  *Many2One  `xmlrpc:"currency_id,omptempty"`
	Date                        *Time      `xmlrpc:"date,omptempty"`
	DaysLeft                    *Int       `xmlrpc:"days_left,omptempty"`
	Description                 *String    `xmlrpc:"description,omptempty"`
	DisplayName                 *String    `xmlrpc:"display_name,omptempty"`
	ExpirationDate              *Time      `xmlrpc:"expiration_date,omptempty"`
	GeneratedCostIds            *Relation  `xmlrpc:"generated_cost_ids,omptempty"`
	Id                          *Int       `xmlrpc:"id,omptempty"`
	InsRef                      *String    `xmlrpc:"ins_ref,omptempty"`
	InsurerId                   *Many2One  `xmlrpc:"insurer_id,omptempty"`
	MessageAttachmentCount      *Int       `xmlrpc:"message_attachment_count,omptempty"`
	MessageChannelIds           *Relation  `xmlrpc:"message_channel_ids,omptempty"`
	MessageFollowerIds          *Relation  `xmlrpc:"message_follower_ids,omptempty"`
	MessageHasError             *Bool      `xmlrpc:"message_has_error,omptempty"`
	MessageHasErrorCounter      *Int       `xmlrpc:"message_has_error_counter,omptempty"`
	MessageHasSmsError          *Bool      `xmlrpc:"message_has_sms_error,omptempty"`
	MessageIds                  *Relation  `xmlrpc:"message_ids,omptempty"`
	MessageIsFollower           *Bool      `xmlrpc:"message_is_follower,omptempty"`
	MessageMainAttachmentId     *Many2One  `xmlrpc:"message_main_attachment_id,omptempty"`
	MessageNeedaction           *Bool      `xmlrpc:"message_needaction,omptempty"`
	MessageNeedactionCounter    *Int       `xmlrpc:"message_needaction_counter,omptempty"`
	MessagePartnerIds           *Relation  `xmlrpc:"message_partner_ids,omptempty"`
	MessageUnread               *Bool      `xmlrpc:"message_unread,omptempty"`
	MessageUnreadCounter        *Int       `xmlrpc:"message_unread_counter,omptempty"`
	Name                        *String    `xmlrpc:"name,omptempty"`
	Notes                       *String    `xmlrpc:"notes,omptempty"`
	Odometer                    *Float     `xmlrpc:"odometer,omptempty"`
	OdometerId                  *Many2One  `xmlrpc:"odometer_id,omptempty"`
	OdometerUnit                *Selection `xmlrpc:"odometer_unit,omptempty"`
	ParentId                    *Many2One  `xmlrpc:"parent_id,omptempty"`
	PurchaserId                 *Many2One  `xmlrpc:"purchaser_id,omptempty"`
	StartDate                   *Time      `xmlrpc:"start_date,omptempty"`
	State                       *Selection `xmlrpc:"state,omptempty"`
	SumCost                     *Float     `xmlrpc:"sum_cost,omptempty"`
	UserId                      *Many2One  `xmlrpc:"user_id,omptempty"`
	VehicleId                   *Many2One  `xmlrpc:"vehicle_id,omptempty"`
	WebsiteMessageIds           *Relation  `xmlrpc:"website_message_ids,omptempty"`
	WriteDate                   *Time      `xmlrpc:"write_date,omptempty"`
	WriteUid                    *Many2One  `xmlrpc:"write_uid,omptempty"`
}

// FleetVehicleLogContracts represents array of fleet.vehicle.log.contract model.
type FleetVehicleLogContracts []FleetVehicleLogContract

// FleetVehicleLogContractModel is the odoo model name.
const FleetVehicleLogContractModel = "fleet.vehicle.log.contract"

// Many2One convert FleetVehicleLogContract to *Many2One.
func (fvlc *FleetVehicleLogContract) Many2One() *Many2One {
	return NewMany2One(fvlc.Id.Get(), "")
}

// CreateFleetVehicleLogContract creates a new fleet.vehicle.log.contract model and returns its id.
func (c *Client) CreateFleetVehicleLogContract(fvlc *FleetVehicleLogContract) (int64, error) {
	ids, err := c.CreateFleetVehicleLogContracts([]*FleetVehicleLogContract{fvlc})
	if err != nil {
		return -1, err
	}
	if len(ids) == 0 {
		return -1, nil
	}
	return ids[0], nil
}

// CreateFleetVehicleLogContract creates a new fleet.vehicle.log.contract model and returns its id.
func (c *Client) CreateFleetVehicleLogContracts(fvlcs []*FleetVehicleLogContract) ([]int64, error) {
	var vv []interface{}
	for _, v := range fvlcs {
		vv = append(vv, v)
	}
	return c.Create(FleetVehicleLogContractModel, vv)
}

// UpdateFleetVehicleLogContract updates an existing fleet.vehicle.log.contract record.
func (c *Client) UpdateFleetVehicleLogContract(fvlc *FleetVehicleLogContract) error {
	return c.UpdateFleetVehicleLogContracts([]int64{fvlc.Id.Get()}, fvlc)
}

// UpdateFleetVehicleLogContracts updates existing fleet.vehicle.log.contract records.
// All records (represented by ids) will be updated by fvlc values.
func (c *Client) UpdateFleetVehicleLogContracts(ids []int64, fvlc *FleetVehicleLogContract) error {
	return c.Update(FleetVehicleLogContractModel, ids, fvlc)
}

// DeleteFleetVehicleLogContract deletes an existing fleet.vehicle.log.contract record.
func (c *Client) DeleteFleetVehicleLogContract(id int64) error {
	return c.DeleteFleetVehicleLogContracts([]int64{id})
}

// DeleteFleetVehicleLogContracts deletes existing fleet.vehicle.log.contract records.
func (c *Client) DeleteFleetVehicleLogContracts(ids []int64) error {
	return c.Delete(FleetVehicleLogContractModel, ids)
}

// GetFleetVehicleLogContract gets fleet.vehicle.log.contract existing record.
func (c *Client) GetFleetVehicleLogContract(id int64) (*FleetVehicleLogContract, error) {
	fvlcs, err := c.GetFleetVehicleLogContracts([]int64{id})
	if err != nil {
		return nil, err
	}
	if fvlcs != nil && len(*fvlcs) > 0 {
		return &((*fvlcs)[0]), nil
	}
	return nil, fmt.Errorf("id %v of fleet.vehicle.log.contract not found", id)
}

// GetFleetVehicleLogContracts gets fleet.vehicle.log.contract existing records.
func (c *Client) GetFleetVehicleLogContracts(ids []int64) (*FleetVehicleLogContracts, error) {
	fvlcs := &FleetVehicleLogContracts{}
	if err := c.Read(FleetVehicleLogContractModel, ids, nil, fvlcs); err != nil {
		return nil, err
	}
	return fvlcs, nil
}

// FindFleetVehicleLogContract finds fleet.vehicle.log.contract record by querying it with criteria.
func (c *Client) FindFleetVehicleLogContract(criteria *Criteria) (*FleetVehicleLogContract, error) {
	fvlcs := &FleetVehicleLogContracts{}
	if err := c.SearchRead(FleetVehicleLogContractModel, criteria, NewOptions().Limit(1), fvlcs); err != nil {
		return nil, err
	}
	if fvlcs != nil && len(*fvlcs) > 0 {
		return &((*fvlcs)[0]), nil
	}
	return nil, fmt.Errorf("fleet.vehicle.log.contract was not found with criteria %v", criteria)
}

// FindFleetVehicleLogContracts finds fleet.vehicle.log.contract records by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleLogContracts(criteria *Criteria, options *Options) (*FleetVehicleLogContracts, error) {
	fvlcs := &FleetVehicleLogContracts{}
	if err := c.SearchRead(FleetVehicleLogContractModel, criteria, options, fvlcs); err != nil {
		return nil, err
	}
	return fvlcs, nil
}

// FindFleetVehicleLogContractIds finds records ids by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleLogContractIds(criteria *Criteria, options *Options) ([]int64, error) {
	ids, err := c.Search(FleetVehicleLogContractModel, criteria, options)
	if err != nil {
		return []int64{}, err
	}
	return ids, nil
}

// FindFleetVehicleLogContractId finds record id by querying it with criteria.
func (c *Client) FindFleetVehicleLogContractId(criteria *Criteria, options *Options) (int64, error) {
	ids, err := c.Search(FleetVehicleLogContractModel, criteria, options)
	if err != nil {
		return -1, err
	}
	if len(ids) > 0 {
		return ids[0], nil
	}
	return -1, fmt.Errorf("fleet.vehicle.log.contract was not found with criteria %v and options %v", criteria, options)
}
