package odoo

import (
	"fmt"
)

// FleetVehicleCost represents fleet.vehicle.cost model.
type FleetVehicleCost struct {
	LastUpdate    *Time      `xmlrpc:"__last_update,omptempty"`
	Amount        *Float     `xmlrpc:"amount,omptempty"`
	AutoGenerated *Bool      `xmlrpc:"auto_generated,omptempty"`
	CompanyId     *Many2One  `xmlrpc:"company_id,omptempty"`
	ContractId    *Many2One  `xmlrpc:"contract_id,omptempty"`
	CostIds       *Relation  `xmlrpc:"cost_ids,omptempty"`
	CostSubtypeId *Many2One  `xmlrpc:"cost_subtype_id,omptempty"`
	CostType      *Selection `xmlrpc:"cost_type,omptempty"`
	CreateDate    *Time      `xmlrpc:"create_date,omptempty"`
	CreateUid     *Many2One  `xmlrpc:"create_uid,omptempty"`
	CurrencyId    *Many2One  `xmlrpc:"currency_id,omptempty"`
	Date          *Time      `xmlrpc:"date,omptempty"`
	Description   *String    `xmlrpc:"description,omptempty"`
	DisplayName   *String    `xmlrpc:"display_name,omptempty"`
	Id            *Int       `xmlrpc:"id,omptempty"`
	Name          *String    `xmlrpc:"name,omptempty"`
	Odometer      *Float     `xmlrpc:"odometer,omptempty"`
	OdometerId    *Many2One  `xmlrpc:"odometer_id,omptempty"`
	OdometerUnit  *Selection `xmlrpc:"odometer_unit,omptempty"`
	ParentId      *Many2One  `xmlrpc:"parent_id,omptempty"`
	VehicleId     *Many2One  `xmlrpc:"vehicle_id,omptempty"`
	WriteDate     *Time      `xmlrpc:"write_date,omptempty"`
	WriteUid      *Many2One  `xmlrpc:"write_uid,omptempty"`
}

// FleetVehicleCosts represents array of fleet.vehicle.cost model.
type FleetVehicleCosts []FleetVehicleCost

// FleetVehicleCostModel is the odoo model name.
const FleetVehicleCostModel = "fleet.vehicle.cost"

// Many2One convert FleetVehicleCost to *Many2One.
func (fvc *FleetVehicleCost) Many2One() *Many2One {
	return NewMany2One(fvc.Id.Get(), "")
}

// CreateFleetVehicleCost creates a new fleet.vehicle.cost model and returns its id.
func (c *Client) CreateFleetVehicleCost(fvc *FleetVehicleCost) (int64, error) {
	ids, err := c.CreateFleetVehicleCosts([]*FleetVehicleCost{fvc})
	if err != nil {
		return -1, err
	}
	if len(ids) == 0 {
		return -1, nil
	}
	return ids[0], nil
}

// CreateFleetVehicleCost creates a new fleet.vehicle.cost model and returns its id.
func (c *Client) CreateFleetVehicleCosts(fvcs []*FleetVehicleCost) ([]int64, error) {
	var vv []interface{}
	for _, v := range fvcs {
		vv = append(vv, v)
	}
	return c.Create(FleetVehicleCostModel, vv)
}

// UpdateFleetVehicleCost updates an existing fleet.vehicle.cost record.
func (c *Client) UpdateFleetVehicleCost(fvc *FleetVehicleCost) error {
	return c.UpdateFleetVehicleCosts([]int64{fvc.Id.Get()}, fvc)
}

// UpdateFleetVehicleCosts updates existing fleet.vehicle.cost records.
// All records (represented by ids) will be updated by fvc values.
func (c *Client) UpdateFleetVehicleCosts(ids []int64, fvc *FleetVehicleCost) error {
	return c.Update(FleetVehicleCostModel, ids, fvc)
}

// DeleteFleetVehicleCost deletes an existing fleet.vehicle.cost record.
func (c *Client) DeleteFleetVehicleCost(id int64) error {
	return c.DeleteFleetVehicleCosts([]int64{id})
}

// DeleteFleetVehicleCosts deletes existing fleet.vehicle.cost records.
func (c *Client) DeleteFleetVehicleCosts(ids []int64) error {
	return c.Delete(FleetVehicleCostModel, ids)
}

// GetFleetVehicleCost gets fleet.vehicle.cost existing record.
func (c *Client) GetFleetVehicleCost(id int64) (*FleetVehicleCost, error) {
	fvcs, err := c.GetFleetVehicleCosts([]int64{id})
	if err != nil {
		return nil, err
	}
	if fvcs != nil && len(*fvcs) > 0 {
		return &((*fvcs)[0]), nil
	}
	return nil, fmt.Errorf("id %v of fleet.vehicle.cost not found", id)
}

// GetFleetVehicleCosts gets fleet.vehicle.cost existing records.
func (c *Client) GetFleetVehicleCosts(ids []int64) (*FleetVehicleCosts, error) {
	fvcs := &FleetVehicleCosts{}
	if err := c.Read(FleetVehicleCostModel, ids, nil, fvcs); err != nil {
		return nil, err
	}
	return fvcs, nil
}

// FindFleetVehicleCost finds fleet.vehicle.cost record by querying it with criteria.
func (c *Client) FindFleetVehicleCost(criteria *Criteria) (*FleetVehicleCost, error) {
	fvcs := &FleetVehicleCosts{}
	if err := c.SearchRead(FleetVehicleCostModel, criteria, NewOptions().Limit(1), fvcs); err != nil {
		return nil, err
	}
	if fvcs != nil && len(*fvcs) > 0 {
		return &((*fvcs)[0]), nil
	}
	return nil, fmt.Errorf("fleet.vehicle.cost was not found with criteria %v", criteria)
}

// FindFleetVehicleCosts finds fleet.vehicle.cost records by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleCosts(criteria *Criteria, options *Options) (*FleetVehicleCosts, error) {
	fvcs := &FleetVehicleCosts{}
	if err := c.SearchRead(FleetVehicleCostModel, criteria, options, fvcs); err != nil {
		return nil, err
	}
	return fvcs, nil
}

// FindFleetVehicleCostIds finds records ids by querying it
// and filtering it with criteria and options.
func (c *Client) FindFleetVehicleCostIds(criteria *Criteria, options *Options) ([]int64, error) {
	ids, err := c.Search(FleetVehicleCostModel, criteria, options)
	if err != nil {
		return []int64{}, err
	}
	return ids, nil
}

// FindFleetVehicleCostId finds record id by querying it with criteria.
func (c *Client) FindFleetVehicleCostId(criteria *Criteria, options *Options) (int64, error) {
	ids, err := c.Search(FleetVehicleCostModel, criteria, options)
	if err != nil {
		return -1, err
	}
	if len(ids) > 0 {
		return ids[0], nil
	}
	return -1, fmt.Errorf("fleet.vehicle.cost was not found with criteria %v and options %v", criteria, options)
}
